# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'wEmotionDetect.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import process


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(807, 501)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(32, 80, 212, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 50, 171, 61))
        self.label.setObjectName("label")

        self.textSentence = QtWidgets.QTextEdit(self.centralwidget)
        self.textSentence.setGeometry(QtCore.QRect(60, 110, 341, 101))
        self.textSentence.setObjectName("textSentence")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 280, 241, 31))
        self.label_2.setObjectName("label_2")

        self.bDetectEmotion = QtWidgets.QPushButton(self.centralwidget)
        self.bDetectEmotion.setGeometry(QtCore.QRect(60, 230, 121, 28))
        self.bDetectEmotion.setObjectName("bDetectEmotion")

        self.listEmotion = QtWidgets.QListView(self.centralwidget)
        self.listEmotion.setGeometry(QtCore.QRect(470, 220, 261, 221))
        self.listEmotion.setObjectName("listEmotion")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(510, 190, 191, 20))
        self.label_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")

        self.rBerth = QtWidgets.QRadioButton(self.centralwidget)
        self.rBerth.setGeometry(QtCore.QRect(60, 340, 95, 20))
        self.rBerth.setObjectName("rBerth")

        self.rNRCL = QtWidgets.QRadioButton(self.centralwidget)
        self.rNRCL.setGeometry(QtCore.QRect(60, 370, 95, 20))
        self.rNRCL.setObjectName("rNRCL")

        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.bDetectEmotion.clicked.connect(lambda: self.ActionButton())


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#f1f1f1;\">Enter Text</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#fcfcfc;\">Select type of analysis:</span></p></body></html>"))
        self.bDetectEmotion.setText(_translate("MainWindow", "Detect Emotion"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#fefefe;\">Emotion Detection</span></p></body></html>"))
        self.rBerth.setText(_translate("MainWindow", "BERTH"))
        self.rNRCL.setText(_translate("MainWindow", "NRCLex"))

    def ActionButton(self):
        text = self.textSentence.toPlainText()
        if self.rBerth.isChecked() | self.rNRCL.isChecked():
            if self.rNRCL.isChecked():
                process.processNRCLexer(text)
            if self.rBerth.isChecked():
                process.processTransformer(text)
        else:
            print('xd nomas')


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    main_window= QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())